# DEVENDRA GURAV AIDS21

In [12]:
import numpy as np

# 1. Array Creation Techniques
print("1. Array Creation Techniques")

# a. Creating an array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print (array_from_list)

# b. Using arange()
array_arange = np.arange(0, 10, 2)
print(array_arange)

# c. Using linspace()
array_linspace = np.linspace(0, 10, 5)  # Divides 0 to 10 into 5 points
print (array_linspace)

# d. Using zeros()
array_zeros = np.zeros((3, 3))
print(array_zeros)

# e. Using ones()
print("array using ones")
array_ones = np.ones((2, 2))
print (array_ones)

# f. Using eye() for identity matrix
print("array using eye")
array_eye = np.eye(3)
print (array_eye)

# g. Using random() for random values
print("array using random")
array_random = np.random.random((3, 3))
print (array_random)

# 2. Different NumPy Methods
print("\n2. NumPy Methods")
print("reshaped array\n")
# a. Reshaping an array
reshaped_array = np.arange(1, 10).reshape(3, 3)
print(reshaped_array)
print("transposed array")
# b. Transposing an array
transposed_array = reshaped_array.T
print(transposed_array)
print("maths opertaion")
# c. Mathematical operations
array_math = np.array([1, 2, 3])
print(array_math + 2)
print (array_math*3)

print (np.sqrt (array_math))

print(" Aggregation methods\n")
# d. Aggregation methods
print(np.sum(array_math))
print(np.mean(array_math))
print(np.max(array_math))
print(np.min(array_math))

# e. Concatenation of arrays
array_a = np.array([1, 2, 3])
print(array_a)
array_b = np.array([4, 5, 6])
print(array_b)
print ("concatenated array")
concat_array = np.concatenate((array_a, array_b))
print(concat_array)

# f. Sorting an array
unsorted_array = np.array([3, 1, 4, 2])
sorted_array = np.sort(unsorted_array)
print ("sorted array")
print(sorted_array)

print(indexed_value)# g. Indexing and Slicing
indexed_value = array_math[1]  # Indexing
print("indexed_value")
print(indexed_value)
sliced_array = array_math[1:3]  # Slicing
print("sliced_array")
print(sliced_array)

# h. Boolean Masking
boolean_mask = array_math > 2
print(boolean_mask)
print(array_math[boolean_mask])

1. Array Creation Techniques
[1 2 3 4 5]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array using ones
[[1. 1.]
 [1. 1.]]
array using eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
array using random
[[0.72079523 0.01407779 0.26189302]
 [0.33816459 0.49231878 0.23149669]
 [0.12321155 0.18063919 0.76723657]]

2. NumPy Methods
reshaped array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
transposed array
[[1 4 7]
 [2 5 8]
 [3 6 9]]
maths opertaion
[3 4 5]
[3 6 9]
[1.         1.41421356 1.73205081]
 Aggregation methods

6
2.0
3
1
[1 2 3]
[4 5 6]
concatenated array
[1 2 3 4 5 6]
sorted array
[1 2 3 4]
2
indexed_value
2
sliced_array
[2 3]
[False False  True]
[3]
